<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('schedule_events', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();

            // Recurring appointments are materialised from a template; deleting the
            // template (series) removes its occurrences with it.
            $table->foreignId('template_id')->nullable()->constrained('event_templates')->cascadeOnDelete();
            // A Work-Session's loose suggestion. Never binding — clearing the task
            // just drops the hint, the session stays.
            $table->foreignId('suggested_task_id')->nullable()->constrained('tasks')->nullOnDelete();

            // appointment | work_session | todo_session | break
            $table->string('type')->default('appointment');
            $table->string('title')->nullable();
            $table->string('color')->default('contour');

            $table->date('date');
            $table->string('start_time', 5); // HH:MM
            $table->string('end_time', 5);   // HH:MM

            // manual (user) | brief (generated by the planning flow)
            $table->string('source')->default('manual');
            // A cancelled occurrence of a recurring series — kept as a tombstone so
            // materialisation never regenerates it.
            $table->boolean('is_cancelled')->default(false);

            $table->timestamps();

            $table->index(['user_id', 'date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('schedule_events');
    }
};
