<?php

namespace App\Models;

use Database\Factories\ScheduleEventFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * A concrete dated block on the timeline. Two families:
 *   • appointment            — added by the user, may come from a recurring template
 *   • work_session / todo_session / break — generated by the Brief (Pomodoro)
 *
 * Times are stored as plain "HH:MM" strings; minute math is done on the fly.
 */
class ScheduleEvent extends Model
{
    /** @use HasFactory<ScheduleEventFactory> */
    use HasFactory;

    public const TYPE_APPOINTMENT = 'appointment';

    public const TYPE_WORK = 'work_session';

    public const TYPE_TODO = 'todo_session';

    public const TYPE_BREAK = 'break';

    public const TYPES = [self::TYPE_APPOINTMENT, self::TYPE_WORK, self::TYPE_TODO, self::TYPE_BREAK];

    /** Default Topografie colour token per type. */
    public const TYPE_COLORS = [
        self::TYPE_APPOINTMENT => 'contour',
        self::TYPE_WORK => 'forest',
        self::TYPE_TODO => 'forest',
        self::TYPE_BREAK => 'ink-faint',
    ];

    protected $fillable = [
        'template_id',
        'suggested_task_id',
        'type',
        'title',
        'color',
        'date',
        'start_time',
        'end_time',
        'source',
        'is_cancelled',
    ];

    protected function casts(): array
    {
        return [
            'date' => 'date',
            'is_cancelled' => 'boolean',
        ];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function template(): BelongsTo
    {
        return $this->belongsTo(EventTemplate::class);
    }

    public function suggestedTask(): BelongsTo
    {
        return $this->belongsTo(Task::class, 'suggested_task_id');
    }

    // ── Scopes ────────────────────────────────────────────────────────

    public function scopeForUser(Builder $query, User $user): Builder
    {
        return $query->where('user_id', $user->id);
    }

    /** Visible events only — cancelled recurring occurrences are hidden. */
    public function scopeVisible(Builder $query): Builder
    {
        return $query->where('is_cancelled', false);
    }

    public function scopeForDay(Builder $query, Carbon|string $date): Builder
    {
        $date = $date instanceof Carbon ? $date->toDateString() : $date;

        return $query->whereDate('date', $date);
    }

    public function scopeForRange(Builder $query, Carbon|string $start, Carbon|string $end): Builder
    {
        $start = $start instanceof Carbon ? $start->toDateString() : $start;
        $end = $end instanceof Carbon ? $end->toDateString() : $end;

        return $query->whereBetween('date', [$start, $end]);
    }

    public function scopeOrdered(Builder $query): Builder
    {
        return $query->orderBy('date')->orderBy('start_time');
    }

    // ── Time helpers ──────────────────────────────────────────────────

    public static function toMinutes(string $hm): int
    {
        [$h, $m] = array_pad(explode(':', $hm), 2, '0');

        return (int) $h * 60 + (int) $m;
    }

    public static function fromMinutes(int $minutes): string
    {
        $minutes = max(0, min(24 * 60, $minutes));

        return sprintf('%02d:%02d', intdiv($minutes, 60), $minutes % 60);
    }

    public function startMinutes(): int
    {
        return self::toMinutes($this->start_time);
    }

    public function endMinutes(): int
    {
        return self::toMinutes($this->end_time);
    }

    public function durationMinutes(): int
    {
        return max(0, $this->endMinutes() - $this->startMinutes());
    }

    public function isAppointment(): bool
    {
        return $this->type === self::TYPE_APPOINTMENT;
    }

    public function isWorkSession(): bool
    {
        return $this->type === self::TYPE_WORK || $this->type === self::TYPE_TODO;
    }

    public function isBreak(): bool
    {
        return $this->type === self::TYPE_BREAK;
    }

    /** Resolve the colour token, falling back to the per-type default. */
    public function colorToken(): string
    {
        return $this->color ?: (self::TYPE_COLORS[$this->type] ?? 'contour');
    }

    // ── Position relative to "now" (for the strip / focus timer) ───────

    private function nowMinutes(Carbon $now): int
    {
        return $now->hour * 60 + $now->minute;
    }

    public function isActive(Carbon $now): bool
    {
        return $this->date->isSameDay($now)
            && $this->nowMinutes($now) >= $this->startMinutes()
            && $this->nowMinutes($now) < $this->endMinutes();
    }

    public function isPast(Carbon $now): bool
    {
        if ($this->date->lessThan($now->copy()->startOfDay())) {
            return true;
        }

        return $this->date->isSameDay($now) && $this->nowMinutes($now) >= $this->endMinutes();
    }

    /** Elapsed fraction 0–1 (only meaningful while active). */
    public function progress(Carbon $now): float
    {
        $duration = $this->durationMinutes();

        if ($duration <= 0) {
            return 0.0;
        }

        $elapsed = $this->nowMinutes($now) - $this->startMinutes();

        return max(0.0, min(1.0, $elapsed / $duration));
    }

    /** Seconds remaining until this event ends (for the live countdown). */
    public function secondsRemaining(Carbon $now): int
    {
        $end = $this->date->copy()->startOfDay()->addMinutes($this->endMinutes());

        return max(0, $now->diffInSeconds($end, false));
    }

    /**
     * Materialise concrete occurrences of recurring templates across a date
     * range. Idempotent: a (template, date) pair that already has any row —
     * including a cancelled tombstone — is skipped, so this never duplicates
     * and never resurrects a deleted occurrence.
     */
    public static function materializeRange(User $user, Carbon $start, Carbon $end): void
    {
        $templates = EventTemplate::forUser($user)->recurring()->get();

        if ($templates->isEmpty()) {
            return;
        }

        // One query for everything already materialised in the window.
        $existing = self::forUser($user)
            ->whereNotNull('template_id')
            ->forRange($start, $end)
            ->get(['template_id', 'date'])
            ->map(fn ($e) => $e->template_id.'|'.$e->date->toDateString())
            ->flip();

        $rows = [];
        $now = now();

        foreach ($templates as $template) {
            for ($date = $start->copy(); $date->lessThanOrEqualTo($end); $date->addDay()) {
                if (! $template->occursOn($date)) {
                    continue;
                }

                if ($existing->has($template->id.'|'.$date->toDateString())) {
                    continue;
                }

                $startTime = $template->default_start ?: '08:00';
                $rows[] = [
                    'user_id' => $user->id,
                    'template_id' => $template->id,
                    'type' => self::TYPE_APPOINTMENT,
                    'title' => $template->name,
                    'color' => $template->color,
                    'date' => $date->toDateString(),
                    'start_time' => $startTime,
                    'end_time' => self::fromMinutes(self::toMinutes($startTime) + $template->duration),
                    'source' => 'manual',
                    'is_cancelled' => false,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        if ($rows !== []) {
            self::insert($rows);
        }
    }
}
